# Generated by Django 5.1.1 on 2025-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
